version: "3"
services:
  db:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: arcticSprintSolutionsDB
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ./dbInit:/docker-entrypoint-initdb.d
      - persistent:/var/lib/mysql
    networks:
      - default
  db_test:
    image: mariadb
    ports:
      - 3310:3306
    environment:
      MYSQL_DATABASE: arcticSprintSolutionsDB
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ./dbInit:/docker-entrypoint-initdb_test.d
      - persistent:/var/lib/mysql_test
    networks:
      - default
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8082:80
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    networks:
      - default
volumes:
  persistent:

